read_sod_file <- function(year) {
  zip_file <- file.path(here::here(),
                        sprintf('data/zipped/SOD/ALL_%d.zip',
                                year))
  csv_file <- sprintf('ALL_%d.csv', year)

  readr::read_csv(unz(zip_file, csv_file)) %>%
    mutate(mainoffice_fl = as.logical(BKMO),
           denovo_fl = as.logical(DENOVO),
           metroarea_fl = as.logical(METROBR),
           microarea_fl = as.logical(MICROBR),
           deposit_cd = factor(BRCENM,
                               levels = c('C', 'E', 'N', 'M'),
                               labels = c('Combined',
                                          'Estimated',
                                          'Non Deposit',
                                          'Main Office')),
           call_cd = factor(CALL, levels = c('CALL', 'TFR')),
           charter_cd = factor(CHARTER,
                               levels = c('FED', 'STATE'),
                               labels = c('Federal', 'State')),
           service_type = factor(BRSERTYPE,
                                 levels = c(11, 12, 13, 21:30),
                                 labels = c('Full service, brick and mortar',
                                            'Full service, retail office',
                                            'Full service, cyber office',
                                            'Limited service, administrative office',
                                            'Limited service, military facility',
                                            'Limited service, drive-through facility',
                                            'Limited service, loan production facility',
                                            'Limited service, consumer credit office',
                                            'Limited service, contractual office',
                                            'Limited service, messenger office',
                                            'Limited service, retail office',
                                            'Limited service, mobile/seasonal office',
                                            'Limited service, trust office')),
           specialization = factor(SPECDESC,
                                   levels = c('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.'),
                                   labels = c('No specializztion group',
                                              'International specialization',
                                              'Agricultural specialization',
                                              'Credit card specialization',
                                              'Commercial lending specialization',
                                              'Mortgage lending specialization',
                                              'Consumer lending specialization',
                                              'Other specialized under 1 billion',
                                              'All other under 1 billion',
                                              'All other over 1 billion',
                                              'Not available')),
           agency = factor(CHRTAGNN,
                           levels = c('Comptroller of the Currency',
                                      'Office of Thrift Supervision',
                                      'State Agency',
                                      'Foreign Country')),
           regulator = factor(REGAGNT,
                              levels = c('FED', 'FDIC', 'OCC', 'OTS', 'NCUA', 'STATE')),
           agency_abb = factor(CHRTAGNT,
                               levels = c('OCC', 'OTS', 'STATE', 'SOVER'))) %>%
    rename(inst_address = ADDRESS,
           address = ADDRESBR,
           assets = ASSETS,
           branch_num = BRNUM,
           cbsa_name = CBSA_DIV_NAMB,
           cert_num = CERT,
           county_name = CNTYNAMB,
           county_fips = CNTYNUMB,
           country_name = CNTRYNAMB,
           country_inst = CNTRYNA,
           deposits = DEPSUMBR,
           deposits_inst = DEPSUM,
           deposits_inst_domestic = DEPDOM,
           id_rssd = RSSDID,
           top_holder = RSSDHCR) %>%
    select(-BKMO, -BRCENM, -SPECDESC, -CHRTAGNT, -REGAGNT,
           -METROBR, -MICROBR, -BRSERTYP)
}
